### ISSUE TITLE
font

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/PythonCertDevel#3]
Hi Chris, 
On the syllabus for each class, can you make the font larger for pre, in-class, and post activities? People didn't seem to necessarily notice when pre switched to in-class...
Hmm, looks like it is hard-coded in each class. I'll do it if you agree this is useful. Search and replace should work for it. I'll have to look at the heading choices, but seems doable.

**Comment by ChrisBarker-NOAA** [comment]
I'll give this a look this evening, if yo huaven't done it yet.

Without getting into custom CSS, maybe we can make it a second-level (or even first level) header, instead of third level, which it may be now.

**Comment by PythonCHB** [comment]
I took a look.

The real problem is the theme we're using -- really doesn't make the different level headers as distinct as I'd like.

So maybe exploring different themes is a good idea.

but fornow, I adjusted it (for the first three classes so far) so that the pre, in-class, and post  are all top-level headers (they were level 2) -- that should make it more clear.

And it was easy, as RST doen'st pre-define the header levels, so I just changed the title to the same style as the sub-sections were:

```
The title of the page
===============
```

I think it's more clear now.

But damn! it messes up the main program page:

https://uwpce-pythoncert.github.io/PythonCertDevel/

The class pages are OK though:

https://uwpce-pythoncert.github.io/IntroPython-2017/

So onward!
